AllCops:
  Include:
    - 'Dangerfile'
    - 'fastlane/Fastfile'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma