AllCops:
  Include:
    - 'fastlane/Dangerfile'
    - 'fastlane/Fastfile'
    - 'fastlane/MasterFastfile'

Metrics/LineLength:
  Max: 150

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma