AllCops:
  Include:
    - 'danger/*'
    - 'fastlane/Fastfile'
    - 'fastlane/MasterFastfile'
    - 'Dangerfile'

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma