# Updated for v0.32.0

disabled_rules:
  # We run the swift_combined_lint_run_script.sh which handles TODO/FIXME/WARN/WARNING independently, so we want to disable this.
  - todo # TODOs and FIXMEs should be resolved.


opt_in_rules:
  - anyobject_protocol # Prefer using AnyObject over class for class-only protocols.
  - array_init #Prefer using Array(seq) over seq.map { $0 } to convert a sequence into an Array.
  - attributes # Attributes should be on their own lines in functions and types, but on the same line as variables and imports.
  - closure_end_indentation # Closure end should have the same indentation as the line that started it.
  - closure_spacing # Closure expressions should have a single space inside each brace.
  - collection_alignment # All elements in a collection literal should be vertically aligned
  - conditional_returns_on_newline # Conditional statements should always return on the next line
  - contains_over_first_not_nil # Prefer contains over first(where:) != nil
  - discouraged_optional_boolean # Prefer non-optional booleans over optional booleans.
  - explicit_init # Explicitly calling .init() should be avoided.
  - empty_count # Prefer checking `isEmpty` over comparing `count` to zero.
  - empty_string # Prefer checking isEmpty over comparing string to an empty string literal.
  - empty_xctest_method # Empty XCTest method should be avoided.
  - fatal_error_message # A fatalError call should have a message.
  - file_name # File name should match a type or extension declared in the file (if any).
  - first_where # "Prefer using `.first(where:)` over `.filter { }.first` in collections.
  - force_unwrapping # Force unwrapping should be avoided.
  - function_default_parameter_at_end # Prefer to locate parameters with defaults toward the end of the parameter list.
  - identical_operands # Comparing two identical operands is likely a mistake.
  - implicitly_unwrapped_optional # Implicitly unwrapped optionals should be avoided when possible.
  - joined_default_parameter # Discouraged explicit usage of the default separator.
  - last_where # Prefer using .last(where:) over .filter { }.last in collections.
  - let_var_whitespace # Let and var should be separated from other statements by a blank line.
  - literal_expression_end_indentation # Array and dictionary literal end should have the same indentation as the line that started it.
  - lower_acl_than_parent # Ensure definitions have a lower access control level than their enclosing parent
  #### - missing_docs # Declarations should be documented.
  - modifier_order # Modifier order should be consistent.
  - multiline_arguments # Arguments should be either on the same line, or one per line.
  - multiline_function_chains # Chained function calls should be either on the same line, or one per line.
  - multiline_parameters # Functions and methods parameters should be either on the same line, or one per line.
  - number_separator # Underscores should be used as thousand separator in large decimal numbers.
  - operator_usage_whitespace # Operators should be surrounded by a single whitespace
  - overridden_super_call # Some overridden methods should always call super" eg: viewDidLoad
  - private_action # IBActions should be private.
  - private_outlet # IBOutlets should be private to avoid leaking UIKit to higher layers.
  - prohibited_super_call # Some methods should not call super" eg: loadView
  - redundant_nil_coalescing # Using nil coalescing operator with nil as rhs is redundant
  - redundant_type_annotation # Variables should not have redundant type annotation
  - sorted_first_last # Prefer using min() or max() over sorted().first or sorted().last
  - sorted_imports # Imports should be sorted
  - switch_case_on_newline # Cases inside a switch should always end on a newline
  - toggle_bool # Prefer `someBool.toggle()` over `someBool = !someBool`.
  - trailing_closure # Trailing closure syntax should be used whenever possible.
  - unneeded_parentheses_in_closure_argument # Parentheses are not needed when declaring closure arguments.
  - untyped_error_in_catch # Catch statements should not declare error variables without type casting.
  - unused_import # All imported modules should be required to make the file compile.
  - unused_private_declaration # Private declarations should be referenced in that file.
  - vertical_parameter_alignment_on_call # Function parameters should be aligned vertically if they're in multiple lines in a method call.


analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self # Instance variables and functions should be explicitly accessed with 'self.'.


colon: # Colons should be next to the identifier when specifying a type and next to the key in dictionary literals.
  apply_to_dictionaries: false # we don't want this rule applied to dictionaries
cyclomatic_complexity: # Complexity of function bodies should be limited.
  ignores_case_statements: true # ignores switch statements
empty_count: warning # Prefer checking `isEmpty` over comparing `count` to zero.
force_cast: warning # Force casts should be avoided.
force_try: warning # Force tries should be avoided.
file_name: # File name should match a type or extension declared in the file (if any).
  excluded: ["Enums.swift"]
file_length: # Files should not span too many lines.
  warning: 1000
  error: 2000
function_body_length: # Functions' bodies should not span too many lines.
  warning: 100
  error: 200
large_tuple: # Tuples shouldn't have too many members
  warning: 3
  error: 4
line_length: # Lines should not span too many characters.
  warning: 150
  error: 400
nesting:
  type_level:
    warning: 1
  statement_level:
    warning: 4
private_outlet: # IBOutlets should be private to avoid leaking UIKit to higher layers.
  allow_private_set: true
trailing_comma: # Trailing commas in arrays and dictionaries should be avoided/enforced.
  mandatory_comma: true # Trailing commas in arrays and dictionaries should be enforced.
trailing_whitespace: #Lines should not have trailing whitespace.
  ignores_empty_lines: true
type_body_length: # Type bodies should not span too many lines.
  warning: 1000
  error: 2000
identifier_name: # Identifier names should only contain alphanumeric characters and start with a lowercase character or should only contain capital letters.
  excluded: # whitelisted exceptions to the above rule
    - id
    - x
    - y


excluded: # what folders should be excluded from analysis?
  - .build # Swift Package Manager
  - Pods # CocoaPods
