#if !canImport(ObjectiveC)
import XCTest

extension BarcodeHeroCoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BarcodeHeroCoreTests = [
        ("testNoThrow", testNoThrow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BarcodeHeroCoreTests.__allTests__BarcodeHeroCoreTests),
    ]
}
#endif
