# frozen_string_literal: true

import_from_git(
  url: 'https://github.com/spothero/Shared-iOS',
  branch: 'fastlane/0.4.0',
  path: 'Fastlane/fastlane/MasterFastfile',
)

default_platform :ios

platform :ios do
  # your app-specific lanes go here!
end
