# frozen_string_literal: true

import 'MasterFastfile'

default_platform :ios

platform :ios do
  # your app-specific lanes go here!

  lane :format do
    sh 'cd .. && swift run swiftformat .'
  end
end
